'use strict';

const WorkerStage = {
  INGESTED: 'INGESTED',
  STT_PENDING: 'STT_PENDING',
  STT_RUNNING: 'STT_RUNNING',
  TRANSLATION_PENDING: 'TRANSLATION_PENDING',
  TRANSLATION_RUNNING: 'TRANSLATION_RUNNING',
  TTS_PENDING: 'TTS_PENDING',
  TTS_RUNNING: 'TTS_RUNNING',
  READY: 'READY',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  STALE: 'STALE'
};

const BackendErrorCode = {
  STT_FAILED: 'STT_FAILED',
  TRANSLATION_FAILED: 'TRANSLATION_FAILED',
  TTS_FAILED: 'TTS_FAILED',
  RATE_LIMITED: 'RATE_LIMITED',
  QUEUE_FULL: 'QUEUE_FULL',
  INVALID_AUDIO: 'INVALID_AUDIO',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  UNSUPPORTED_LANGUAGE: 'UNSUPPORTED_LANGUAGE',
  MODEL_UNAVAILABLE: 'MODEL_UNAVAILABLE',
  TIMEOUT: 'TIMEOUT',
  CANCELLED: 'CANCELLED',
  STALE_GENERATION: 'STALE_GENERATION',
  INTERNAL: 'INTERNAL'
};

const SessionStatus = {
  ACTIVE: 'ACTIVE',
  DRAINING: 'DRAINING',
  EXPIRED: 'EXPIRED',
  CLOSED: 'CLOSED'
};

module.exports = {
  WorkerStage,
  BackendErrorCode,
  SessionStatus
};
